name = "authless-fastmcp-server"
compatibility_date = "2024-12-09"

# For Remote MCP Server deployment
[build]
command = "uv sync && uv run python -m authless_fastmcp_server.main"
publish = "./dist"

[env.production]
name = "authless-fastmcp-server"

[env.preview]  
name = "authless-fastmcp-server-preview"

# Environment variables
[vars]
HOST = "0.0.0.0"
PORT = "8000"
