name = "authless-fastmcp-server"
compatibility_date = "2024-12-09"
main = "src/index.ts"

[build]
command = "npm run build"

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"

# Environment variables for preview
[env.preview.vars]
ENVIRONMENT = "preview"
